
<h1>Registration page</h1>

<form action="<?php echo $block->getFormAction() ?>" method="post">
    <label>First Name : </label>
    <input name="firstname" type="text" required>
    <label>Last Name : </label>
    <input name="lastname" type="text" required>
    <label>Email : </label>
    <input name="email" type="email" required>
    <label>Phone No : </label>
    <input name="Phoneno" type="tel" required>
    <button type="submit">Submit</button>
</form>
