<!doctype HTML>
<html>
	<head>
		<title>Registration Form</title>
	</head>
	<body>
		<form action=<?php echo $block->getBaseUrl()?><?php echo $block->getFormAction()?> method= "POST" id="form-validate">
			<label>First Name : </label></br>
			<input type="text" name="fname" id="fname" required/></br>
			<label>Last Name : </label></br>
			<input type="text" name="lname" id="lname" required/></br>
			<label>Email : </label></br>
			<input type="email" name="email" id="email" required/></br>
			<label>Mobile No : </label></br>
			<input type="tel" name="mob" id="mob" required/></br>
			<button type="submit" value="Submit">Submit</button>
			 <a href=<?php echo $block->getBaseUrl()?>crud/index/view>View</a></br>
		</form>
	</body>
</html>
