<?php
echo "<h2>All Customers</h2>";
$collection = $block->getDataCollection();

?>

<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-id{width:2%} .post-name{width:30%}
    
    </style>
    
    <table>
      <tr>
        <th>Id</th>
        <th>FName</th>
        <th>LName</th> 
        <th>Email</th> 
        <th>Mobile No</th> 
        <th>Delete</th> 
      </tr>
        <?php
            foreach ($collection as $data)
            {
                echo "<tr>";
                echo "<td><a href=".$block->getBaseUrl().'crud/index/edit?id='.$data->getPostId().">".$data->getPostId()."</a></td>"; 
                echo "<td>".$data->getFname()."</td>";
                echo "<td>".$data->getLname()."</td>";
                echo "<td>".$data->getEmail()."</td>";  
                echo "<td>".$data->getMob()."</td>"; 
                echo "<td><a href=".$block->getBaseUrl().'crud/index/delete?id='.$data->getPostId().">".'Delete'."</a></td>"; 
                     
                echo "</tr>";
                    
                
            }
        ?>
    </table>
    
 
