<?php
echo "Current page Url : ".$this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
echo"<br>";
echo "Base Url : ".$block->getBaseUrl(); 
echo"<br>";


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$fileSystem = $objectManager->create('\Magento\Framework\Filesystem');
$mediaPath = $fileSystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA)->getAbsolutePath();
echo "Media Url : ".$mediaPath;

echo"<br>";