<!-- < ?php
$productCollection = $block->getProductCollection();
foreach ($productCollection as $product) {
    print_r($product->getData());   
    echo"hello";  
    echo "<br>";
}
?> -->
<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>

<table>
  <tr>
    <th>ProductName</th>
    <th>SKU</th>
    <th>Price</th> 
  </tr>
    <?php
        $productCollection = $block->getProductCollection();
        foreach ($productCollection as $product)
        {
            echo "<tr>";
                echo "<td><a href=".$product->getProductUrl().">".$product->getName()."</a></td>";
                echo "<td>".$product->getSKU()."</td>";
                echo "<td>".$product->getPrice()."</td>";        
                echo "</tr>";
        }
    ?>
</table>

