 <!-- < ?php
$categoryCollection = $block->getCategoryCollection();
foreach ($categoryCollection as $category) {
    // print_r($category->getName());   
    echo "<a href=".$category->getUrl().">".$category->getName()."</a>";
    echo "<br>";
}
  ?> -->
<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>
<table>
  <tr>
    <th>CategoriesName</th>
  </tr>
    <?php
    $categoryCollection = $block->getCategoryCollection();
        foreach ($categoryCollection as $category){
            echo "<tr>";
                echo "<td><a href=".$category->getCategoryUrl().">".$category->getName()."</a></td>";  
                echo "</tr>";
        }
    ?>
</table>

